# Generated by Django 4.1.7 on 2023-06-02 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_calendarevent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
